/**
 * Stat Battle — an animated bar-chart race (ranking-over-time) generated by the
 * brain. The data is GAME-AGNOSTIC: entities with values at sparse time
 * keyframes; the renderer interpolates between them for a smooth race.
 */

export type RaceEntity = { name: string; color: string };

// Raw shape returned by the brain / API (values as an array — JSON friendly).
export type RaceKeyframeRaw = { time: number; values: { name: string; value: number }[] };
export type RaceRaw = {
  title: string;
  subtitle?: string;
  valueLabel?: string;
  unitPrefix?: string;
  unitSuffix?: string;
  timeLabel?: string;
  entities: RaceEntity[];
  keyframes: RaceKeyframeRaw[];
};

// Normalized client model — keyframe values as a name→value map, sorted by time.
export type RaceFrame = { time: number; values: Record<string, number> };
export type RaceData = {
  title: string;
  subtitle: string;
  valueLabel: string;
  unitPrefix: string;
  unitSuffix: string;
  timeLabel: string;
  entities: RaceEntity[];
  frames: RaceFrame[]; // sorted ascending by time
  topN: number; // visible bars
  durationSec: number; // race length (excl. the end hold)
};

// A readable, high-contrast palette assigned by index when the brain omits colors.
export const PALETTE = [
  "#e6194B", "#3cb44b", "#4363d8", "#f58231", "#911eb4", "#42d4f4",
  "#f032e6", "#bfef45", "#fabed4", "#469990", "#9A6324", "#800000",
  "#808000", "#000075", "#e6beff", "#dcbeff", "#aaffc3", "#ffd8b1",
];
