"use client";

/**
 * Client → brain bridge for the flag game. The game is ALWAYS generated by
 * Isaac's brain (POST /api/games/flags) from a natural-language request, so it's
 * fully dynamic (any region/difficulty/count/theme) and nothing is hardcoded.
 */

export type Difficulty = "easy" | "medium" | "hard";
export type Round = { code: string; name: string; aliases: string[]; difficulty: Difficulty; flag: string };
export type Game = { title: string; secondsPerRound: number; rounds: Round[] };

/** Quick-start presets — each is just a natural request the brain interprets. */
export const PRESETS: { label: string; request: string }[] = [
  { label: "World", request: "A worldwide mix of 12 flags, easy to hard." },
  { label: "Europe", request: "12 European country flags, easy to hard." },
  { label: "Asia", request: "12 Asian country flags, easy to hard." },
  { label: "Africa", request: "12 African country flags, easy to hard." },
  { label: "Americas", request: "12 flags from the Americas, easy to hard." },
  { label: "Hard", request: "12 hard, obscure, tricky-to-recognize country flags." },
  { label: "Random", request: "12 completely random country flags from all over the world." },
];

async function post(payload: Record<string, unknown>): Promise<Game> {
  try {
    const res = await fetch("/api/games/flags", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new Error("generation failed");
    const data = (await res.json()) as Partial<Game>;
    return {
      title: data.title || "Flags",
      secondsPerRound: data.secondsPerRound && data.secondsPerRound > 0 ? data.secondsPerRound : 7,
      rounds: Array.isArray(data.rounds) ? data.rounds : [],
    };
  } catch {
    return { title: "Flags", secondsPerRound: 7, rounds: [] };
  }
}

/** A brain-curated set from a natural request. */
export function buildGame(request: string): Promise<Game> {
  return post({ request });
}

/** EVERY country in the world, ordered easiest → hardest (for "Continue"). */
export function buildAllCountries(): Promise<Game> {
  return post({ all: true });
}
