"use client";

/**
 * Client → brain bridge for the flag game. The game is ALWAYS generated by
 * Isaac's brain (POST /api/games/flags) from a natural-language request, so it's
 * fully dynamic (any region/difficulty/count/theme) and nothing is hardcoded.
 */

import { reportBillingStatus, refreshCredits } from "@/lib/billing/bus";

export type Difficulty = "easy" | "medium" | "hard";
export type Round = { code: string; name: string; aliases: string[]; difficulty: Difficulty; flag: string };
export type Game = { title: string; subtitle?: string; secondsPerRound: number; rounds: Round[] };

/**
 * Quick-start presets — each is just a natural request the brain interprets.
 * Region/category chips request the FULL set (no fixed count) so the brain
 * returns every matching country; "World"/"Random" stay a varied worldwide mix.
 */
export const PRESETS: { label: string; request: string }[] = [
  { label: "World", request: "A varied worldwide mix of flags, easy to hard." },
  { label: "Europe", request: "European country flags, easy to hard." },
  { label: "Asia", request: "Asian country flags, easy to hard." },
  { label: "Africa", request: "African country flags, easy to hard." },
  { label: "Americas", request: "Flags of the Americas, easy to hard." },
  { label: "Hard", request: "Hard, obscure, tricky-to-recognize flags from around the world." },
  { label: "Random", request: "A completely random worldwide mix of flags." },
];

async function post(payload: Record<string, unknown>): Promise<Game> {
  try {
    const res = await fetch("/api/games/flags", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) {
      reportBillingStatus(res.status);
      throw new Error("generation failed");
    }
    const data = (await res.json()) as Partial<Game>;
    refreshCredits();
    return {
      title: data.title || "Flags",
      subtitle: typeof data.subtitle === "string" && data.subtitle.trim() ? data.subtitle.trim() : undefined,
      secondsPerRound: data.secondsPerRound && data.secondsPerRound > 0 ? data.secondsPerRound : 7,
      rounds: Array.isArray(data.rounds) ? data.rounds : [],
    };
  } catch {
    return { title: "Flags", secondsPerRound: 7, rounds: [] };
  }
}

/** A brain-curated set from a natural request. */
export function buildGame(request: string): Promise<Game> {
  return post({ request });
}

/** EVERY country in the world, ordered easiest → hardest (for "Continue"). */
export function buildAllCountries(): Promise<Game> {
  return post({ all: true });
}

/* ── Video Direct: plan a full game from a prompt with OPUS, for a directly-generated
 *    recap video (no play). Gated server-side (credits + the 2/month premium cap). ── */
export type PlanResult =
  | { ok: true; game: Game; premium: boolean }
  | { ok: false; reason: "auth" | "credits" | "video_limit" | "failed" };

/** READ-ONLY pre-flight (no charge, no Opus): verify the user is authed, can afford the
 *  plan, and has premium quota BEFORE firing the expensive generate — mirrors the stat
 *  battle. Fails OPEN on transient errors (the real gated call still verifies). */
export async function preflightVideoGame(request: string, voice: string): Promise<{ ok: boolean; reason?: "auth" | "credits" | "video_limit" }> {
  let res: Response;
  try {
    res = await fetch("/api/games/plan", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ request, voice, preflight: true }),
    });
  } catch {
    return { ok: true }; // offline/transient → let the gated call decide
  }
  if (res.ok) return { ok: true };
  if (res.status === 401) return { ok: false, reason: "auth" };
  if (res.status === 402) {
    const j = (await res.json().catch(() => ({}))) as { error?: string };
    return { ok: false, reason: j.error === "video_limit" ? "video_limit" : "credits" };
  }
  return { ok: true }; // unknown → let the gated call decide
}

export async function planVideoGame(request: string, voice: string): Promise<PlanResult> {
  let res: Response;
  try {
    res = await fetch("/api/games/plan", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ request, voice }),
    });
  } catch {
    return { ok: false, reason: "failed" };
  }
  if (res.status === 401) return { ok: false, reason: "auth" };
  if (res.status === 402) {
    const j = (await res.json().catch(() => ({}))) as { error?: string };
    return { ok: false, reason: j.error === "video_limit" ? "video_limit" : "credits" };
  }
  if (res.status === 429) {
    reportBillingStatus(429);
    return { ok: false, reason: "failed" };
  }
  if (!res.ok) return { ok: false, reason: "failed" };
  const data = (await res.json()) as Partial<Game> & { error?: boolean; premium?: boolean };
  if (data.error || !Array.isArray(data.rounds) || !data.rounds.length) return { ok: false, reason: "failed" };
  refreshCredits();
  return {
    ok: true,
    premium: !!data.premium,
    game: {
      title: data.title || "Flags",
      subtitle: typeof data.subtitle === "string" && data.subtitle.trim() ? data.subtitle.trim() : undefined,
      secondsPerRound: data.secondsPerRound && data.secondsPerRound > 0 ? data.secondsPerRound : 7,
      rounds: data.rounds as Round[],
    },
  };
}
